// export const GET_USERS = 'GET_USERS';
// export const USERS_ERROR = 'USERS_ERROR'

export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_ERROR = 'GET_RECIPES_ERROR'